language: php

php:
  - '7.4'

env:
  global:
    - XDEBUG_MODE=coverage

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

after_success:
  - bash <(curl -s https://codecov.io/bash)